# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('app_name', models.CharField(max_length=256)),
                ('package_name', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('use_time', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set([('uuid', 'start_date', 'start_time')]),
        ),
    ]
