# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('cellphone', models.CharField(max_length=15)),
            ],
        ),
    ]
